AllCops:
  NewCops: enable
  SuggestExtensions: false

Naming/FileName:
 Exclude:
   - lib/rubocop-truffleruby.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
