# frozen_string_literal: true

require_relative 'truffleruby/replace_with_primitive_class'
require_relative 'truffleruby/replace_with_primitive_equal'
require_relative 'truffleruby/replace_with_primitive_is_a'
require_relative 'truffleruby/replace_with_primitive_nil'
require_relative 'truffleruby/replace_with_primitive_true_and_false_predicates'
