# frozen_string_literal: true

require_relative 'truffleruby/replace_with_primitive_nil'
require_relative 'truffleruby/replace_with_primitive_object_class'
require_relative 'truffleruby/replace_with_primitive_object_equal'
require_relative 'truffleruby/replace_with_primitive_object_kind_of'
